### ISSUE TITLE
Broken syntax highlighting of code examples in function docs

### ISSUE THREAD

**Issue by woylie** [elixir-editors/elixir-sublime-syntax#31] opened 2021-09-16 01:53 UTC
I'm on the latest version of the `azizk/add-surface-syntax` branch at the moment. I don't know whether this is already known or whether this is already fixed in another branch, but the highlighting of code examples in function docs looks broken.

![image](https://user-images.githubusercontent.com/13847569/133536414-46e36161-1ee8-46dd-9057-99a37ac97760.png)

**Comment by azizk** [comment] 2021-09-16 05:48
Oh that's a Markdown issue, or actually more a limitation of the highlighting engine. The engine cannot remove the heredoc indentation before matching the inside using the Markdown definition. What happens then is that the ` _` starts an italic character sequence and it doesn't stop without the closing `_ `.

There's no real fix for this afaics except for not using Markdown.sublime-syntax at all. Maybe we could try to match only a working subset of Markdown ourselves, but that's for a later time.

Thanks for reporting and for trying out the dev branch!

**Comment by princemaple** [comment] 2021-09-16 05:49
Yeah we might better off not use markdown for docs at all.

**Comment by azizk** [comment] 2021-12-18 14:12
Note: this issue persists in ST 4121.

**Comment by woylie** [comment] 2021-12-19 03:36
I checked it, and there still seems to be a problem, but does not seem to be related to the code example in the doc string.

This is fine:

```elixir
  @doc """
  Whatever

  ## Example

  You can do something here.

      def index(conn, _) do
        conn
        |> assign(:page_title, "I am the page now.")
        |> render("index.html")
      end
  """
```

![image](https://user-images.githubusercontent.com/13847569/146662960-9c27c912-d8de-4326-913f-3ad67790492f.png)

But if I add a list, the highlighting after is messed up.

```elixir
  @doc """
  Whatever

  - hello

  ## Example

  You can do something here.

      def index(conn, _) do
        conn
        |> assign(:page_title, "I am the page now.")
        |> render("index.html")
      end
  """
```

![image](https://user-images.githubusercontent.com/13847569/146662941-f0574c5a-10d8-4442-bfa4-66094dcb0519.png)

**Comment by azizk** [comment] 2021-12-19 22:41
Thanks for checking. I can confirm what you're seeing. Looks like I'll have to remove Markdown highlighting from `@doc` comments altogether, because the engine isn't capable of doing this correctly. Pity... :-/

**Comment by azizk** [comment] 2022-09-02 11:40
@woylie Hi! Are you still using ST for Elixir? If so can you please try out my [v2.4.0 branch](https://github.com/elixir-editors/elixir-sublime-syntax/tree/aziz/v2.4.0)? Markdown highlighting has been removed unfortunately. But a plethora of other features and goodies have been added. Would appreciate it if you could test out everything that's new! :smiley:

**Comment by woylie** [comment] 2022-09-17 03:04
Hey @azizk,

I just checked out your branch. Everything looks fine at first glance, I'll work with this and let you know if I notice something.

One thing, though: Previously, docs and moduledocs would appear white in my theme (ayu mirage). Now, they appear yellow, which I don't like. I don't know how colors work in themes, but I would prefer a muted color (I actually preferred the grey I had in the Elixir.tmbundle package over the white, even). Is this something that can be modified?

<img width="498" alt="imagen" src="https://user-images.githubusercontent.com/13847569/190838122-c8cfffaa-bd02-47e1-a051-bcc8fc66c7d8.png">

**Comment by princemaple** [comment] 2022-09-17 03:26
Hey I use ayu mirage as well :) ❤️ 

It used to use markdown syntax and use the markdown coloring. So the doc block would render the same as how a .md file would render.

Now that it's back to simple string, you are seeing the ordinary string coloring.

You can put your caret in the moduledoc, press ctrl+alt+shift+p to trigger scope display. (I'm not on the branch so the scopes here may be different.)

![image](https://user-images.githubusercontent.com/1329716/190838717-f3068873-8b58-4c5c-a2f8-5f8edcfa82e9.png)

And grab an appropriate scope and use it in your color scheme customization.

![image](https://user-images.githubusercontent.com/1329716/190838730-742fcc89-d564-4fe7-9778-e90ed9627c15.png)

**Closed** 2022-10-24 01:20 UTC
Labels: bug
